### ISSUE TITLE
Getting "Maximum call stack size exceeded" for validate/inspect commands

### ISSUE THREAD

**Issue by Ebeid** [readmeio/rdme#813] opened 2023-05-05 18:16 UTC
Getting "Maximum call stack size exceeded" for validate/inspect commands. Using version 8.6.3

**Comment by kanadgupta** [comment] 2023-05-05 18:45
Hi @Ebeid! Are you seeing this error before or after selecting an API definition? If it's prior to the selection, this is likely a duplicate of #780.

**Comment by Ebeid** [comment] 2023-05-05 18:54
After
```
rdme openapi:inspect ~/Downloads/swagger.json
✖ Validating the API definition located at /Users/eelsayed/Downloads/swagger.json...

Maximum call stack size exceeded
```

**Comment by kanadgupta** [comment] 2023-05-05 19:16
Can you send across the file?

**Comment by Ebeid** [comment] 2023-05-15 15:26
I'm sorry I can't share that json file. The issue seems reproducible with other files that used work before.

**Comment by kanadgupta** [comment] 2023-05-15 16:20
We need a reproducible example in order to fix the issue. Even a API definition file with redacted or placeholder data would be helpful.

Closing this out but happy to revisit this once we have an example!

**Closed** 2023-05-15 16:20 UTC
Labels: question, command:openapi
